services:
  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - path: "./.env"
        required: true
      - path: "./.env.local"
        required: false
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}